const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');const {URL}=require('url');const {Pool}=require('pg');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,PUBLIC=path.join(ROOT,'public');
const APP_NAME=process.env.APP_NAME||'Randevum';const SESSION_DAYS=Number(process.env.SESSION_DAYS||14);const DATABASE_URL=process.env.DATABASE_URL;
let pool=null;
const memory={users:[],businesses:[],services:[],hours:[],appointments:[],sessions:[]};
function id(p='id'){return p+'_'+crypto.randomBytes(12).toString('hex')}
function slugify(s){return String(s).toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ü/g,'u').replace(/ş/g,'s').replace(/ö/g,'o').replace(/ç/g,'c').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48)||'berber'}
function hashPassword(p,s=crypto.randomBytes(16).toString('hex')){return s+':'+crypto.scryptSync(p,s,64).toString('hex')}
function verifyPassword(p,stored){const [s,h]=String(stored).split(':');if(!s||!h)return false;const a=crypto.scryptSync(p,s,64),b=Buffer.from(h,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function cookies(req){const o={};for(const x of (req.headers.cookie||'').split(';')){const i=x.indexOf('=');if(i>0)o[x.slice(0,i).trim()]=decodeURIComponent(x.slice(i+1).trim())}return o}
function json(res,status,obj,headers={}){const body=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers});res.end(body)}
function text(res,status,b,ct='text/plain; charset=utf-8'){res.writeHead(status,{'Content-Type':ct});res.end(b)}
async function body(req){return new Promise((resolve,reject)=>{let r='';req.on('data',c=>{r+=c;if(r.length>1e6){reject(new Error('payload too large'));req.destroy()}});req.on('end',()=>{try{resolve(r?JSON.parse(r):{})}catch{reject(new Error('invalid json'))}});req.on('error',reject)})}
async function initDb(){if(!DATABASE_URL){if(process.env.NODE_ENV==='production')throw new Error('DATABASE_URL eksik. Production ortamında PostgreSQL zorunludur.');return;}pool=new Pool({connectionString:DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});await pool.query(`CREATE TABLE IF NOT EXISTS users(id text primary key,email text unique not null,password_hash text not null,created_at timestamptz not null default now());CREATE TABLE IF NOT EXISTS businesses(id text primary key,user_id text unique references users(id) on delete cascade,name text not null,description text,address text,phone text,logo text,slug text unique not null,created_at timestamptz not null default now());CREATE TABLE IF NOT EXISTS services(id text primary key,business_id text references businesses(id) on delete cascade,name text not null,duration int not null,price numeric not null);CREATE TABLE IF NOT EXISTS hours(id text primary key,business_id text references businesses(id) on delete cascade,day text not null,open boolean not null,open_time text not null,close_time text not null);CREATE TABLE IF NOT EXISTS appointments(id text primary key,business_id text references businesses(id) on delete cascade,service_id text references services(id),date date not null,time text not null,customer_name text not null,phone text not null,note text,status text not null,created_at timestamptz not null default now());CREATE INDEX IF NOT EXISTS appointments_lookup ON appointments(business_id,date,time);CREATE TABLE IF NOT EXISTS sessions(id text primary key,user_id text references users(id) on delete cascade,expires_at timestamptz not null);CREATE INDEX IF NOT EXISTS sessions_exp ON sessions(expires_at);`)}
async function q(sql,params=[]){if(pool){const r=await pool.query(sql,params);return r.rows}return []}
function fallback(name){return memory[name]}
async function userBySession(req){const sid=cookies(req).randevum_session;if(!sid)return null;if(pool){const r=await q('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=$1 AND s.expires_at>now()',[sid]);return r[0]||null}const s=memory.sessions.find(x=>x.id===sid&&new Date(x.expiresAt)>new Date());return s?memory.users.find(u=>u.id===s.userId)||null:null}
async function businessForUser(u){if(pool){const r=await q('SELECT * FROM businesses WHERE user_id=$1',[u.id]);return r[0]||null}return memory.businesses.find(b=>b.userId===u.id)||null}
function cleanB(b){return b&&{id:b.id,name:b.name,description:b.description||'',address:b.address||'',phone:b.phone||'',logo:b.logo||'',slug:b.slug,publicUrl:'/b/'+b.slug}}
async function uniqueSlug(name){let base=slugify(name),s=base,n=1;while((pool?(await q('SELECT 1 FROM businesses WHERE slug=$1',[s])).length:memory.businesses.some(b=>b.slug===s)))s=base+'-'+(++n);return s}
function cookie(sid,max=SESSION_DAYS*86400){const secure=process.env.NODE_ENV==='production'?' Secure;':'';return `randevum_session=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${max};${secure}`}
const rate=new Map();function limited(key,max=10,windowMs=600000){const now=Date.now(),a=rate.get(key)||[];const fresh=a.filter(t=>now-t<windowMs);fresh.push(now);rate.set(key,fresh);return fresh.length>max}
async function register(x){const email=String(x.email||'').trim().toLowerCase(),password=String(x.password||''),name=String(x.businessName||'').trim();if(name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8)throw Object.assign(new Error('İşletme adı, geçerli e-posta ve en az 8 karakterli şifre gerekli.'),{status:400});if(pool){if((await q('SELECT 1 FROM users WHERE email=$1',[email])).length)throw Object.assign(new Error('Bu e-posta zaten kayıtlı.'),{status:409});const u=id('usr'),b=id('biz'),slug=await uniqueSlug(name);await q('INSERT INTO users(id,email,password_hash) VALUES($1,$2,$3)',[u,email,hashPassword(password)]);await q('INSERT INTO businesses(id,user_id,name,description,address,phone,logo,slug) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[b,u,name,'Profesyonel berber hizmeti.','','','',slug]);for(const [n,d,p] of [['Saç Kesimi',30,300],['Sakal Tıraşı',20,200],['Saç + Sakal',50,450]])await q('INSERT INTO services(id,business_id,name,duration,price) VALUES($1,$2,$3,$4,$5)',[id('svc'),b,n,d,p]);const days=['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'];for(let i=0;i<7;i++)await q('INSERT INTO hours(id,business_id,day,open,open_time,close_time) VALUES($1,$2,$3,$4,$5,$6)',[id('hr'),b,days[i],i<6,'09:00',i<5?'20:00':'18:00']);return {user:{id:u,email},business:{id:b,name,slug}}}
if(memory.users.some(u=>u.email===email))throw Object.assign(new Error('Bu e-posta zaten kayıtlı.'),{status:409});const u={id:id('usr'),email,passwordHash:hashPassword(password),createdAt:new Date().toISOString()},b={id:id('biz'),userId:u.id,name,description:'Profesyonel berber hizmeti.',address:'',phone:'',logo:'',slug:await uniqueSlug(name),createdAt:new Date().toISOString()};memory.users.push(u);memory.businesses.push(b);for(const [n,d,p] of [['Saç Kesimi',30,300],['Sakal Tıraşı',20,200],['Saç + Sakal',50,450]])memory.services.push({id:id('svc'),businessId:b.id,name:n,duration:d,price:p});['Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi','Pazar'].forEach((day,i)=>memory.hours.push({id:id('hr'),businessId:b.id,day,open:i<6,openTime:'09:00',closeTime:i<5?'20:00':'18:00'}));return {user:u,business:b}}
async function createSession(userId){const sid=id('ses'),exp=new Date(Date.now()+SESSION_DAYS*86400000);if(pool)await q('INSERT INTO sessions(id,user_id,expires_at) VALUES($1,$2,$3)',[sid,userId,exp]);else memory.sessions.push({id:sid,userId,expiresAt:exp.toISOString()});return sid}
async function api(req,res,url){const p=url.pathname,m=req.method,key=(req.socket.remoteAddress||'unknown')+':'+p;if(['POST','PUT','PATCH','DELETE'].includes(m)&&limited(key,60,60000))return json(res,429,{error:'Çok fazla istek. Lütfen biraz sonra tekrar deneyin.'});
if(m==='POST'&&p==='/api/register'){try{const r=await register(await body(req));const sid=await createSession(r.user.id);return json(res,201,{business:cleanB(r.business)},{'Set-Cookie':cookie(sid)})}catch(e){return json(res,e.status||500,{error:e.message||'Kayıt sırasında hata oluştu.'})}}
if(m==='POST'&&p==='/api/login'){const x=await body(req),email=String(x.email||'').trim().toLowerCase(),password=String(x.password||'');let u=null;if(pool){const r=await q('SELECT * FROM users WHERE email=$1',[email]);u=r[0]}else u=memory.users.find(v=>v.email===email);if(!u||!verifyPassword(password,u.password_hash||u.passwordHash))return json(res,401,{error:'E-posta veya şifre hatalı.'});const b=await businessForUser(u),sid=await createSession(u.id);return json(res,200,{business:cleanB(b)},{'Set-Cookie':cookie(sid)})}
if(m==='POST'&&p==='/api/logout'){const sid=cookies(req).randevum_session;if(pool)await q('DELETE FROM sessions WHERE id=$1',[sid]);else memory.sessions=memory.sessions.filter(s=>s.id!==sid);return json(res,200,{ok:true},{'Set-Cookie':cookie('',0)})}
const u=await userBySession(req);if(p==='/api/me'&&m==='GET'){if(!u)return json(res,401,{error:'Oturumunuz sona ermiş.'});const b=await businessForUser(u);if(pool){const [sv,hr,ap]=await Promise.all([q('SELECT id,name,duration,price FROM services WHERE business_id=$1 ORDER BY name',[b.id]),q('SELECT id,day,open,open_time "openTime",close_time "closeTime" FROM hours WHERE business_id=$1 ORDER BY id',[b.id]),q('SELECT id,date::text date,time,customer_name "customerName",phone,note,service_id "serviceId",status,created_at "createdAt" FROM appointments WHERE business_id=$1 ORDER BY date,time',[b.id])]);return json(res,200,{business:cleanB(b),services:sv,hours:hr,appointments:ap})}const sv=memory.services.filter(s=>s.businessId===b.id),hr=memory.hours.filter(h=>h.businessId===b.id),ap=memory.appointments.filter(a=>a.businessId===b.id);return json(res,200,{business:cleanB(b),services:sv,hours:hr,appointments:ap})}
if(p==='/api/business'&&m==='PUT'){if(!u)return json(res,401,{error:'Oturumunuz sona ermiş.'});const b=await businessForUser(u),x=await body(req);const vals=[String(x.name||b.name).trim(),String(x.description||''),String(x.address||''),String(x.phone||''),String(x.logo||'')];if(!vals[0])return json(res,400,{error:'İşletme adı gerekli.'});if(pool){await q('UPDATE businesses SET name=$1,description=$2,address=$3,phone=$4,logo=$5 WHERE id=$6',[...vals,b.id])}else Object.assign(b,{name:vals[0],description:vals[1],address:vals[2],phone:vals[3],logo:vals[4]});return json(res,200,{business:cleanB({...b,name:vals[0],description:vals[1],address:vals[2],phone:vals[3],logo:vals[4]})})}
if(p==='/api/services'&&m==='POST'){if(!u)return json(res,401,{error:'Oturumunuz sona ermiş.'});const b=await businessForUser(u),x=await body(req),name=String(x.name||'').trim(),duration=Math.max(5,Math.min(480,Number(x.duration||30))),price=Math.max(0,Number(x.price||0));if(!name)return json(res,400,{error:'Hizmet adı gerekli.'});const s={id:id('svc'),businessId:b.id,name,duration,price};if(pool){await q('INSERT INTO services(id,business_id,name,duration,price) VALUES($1,$2,$3,$4,$5)',[s.id,b.id,name,duration,price])}else memory.services.push(s);return json(res,201,{service:s})}
let mm=p.match(/^\/api\/services\/([^/]+)$/);if(mm&&m==='DELETE'){if(!u)return json(res,401,{error:'Oturumunuz sona ermiş.'});const b=await businessForUser(u);if(pool)await q('DELETE FROM services WHERE id=$1 AND business_id=$2',[mm[1],b.id]);else memory.services=memory.services.filter(s=>!(s.id===mm[1]&&s.businessId===b.id));return json(res,200,{ok:true})}
if(p==='/api/hours'&&m==='PUT'){if(!u)return json(res,401,{error:'Oturumunuz sona ermiş.'});const b=await businessForUser(u),x=await body(req);for(const h of x.hours||[]){if(pool)await q('UPDATE hours SET open=$1,open_time=$2,close_time=$3 WHERE id=$4 AND business_id=$5',[!!h.open,String(h.openTime||'09:00'),String(h.closeTime||'18:00'),h.id,b.id]);else{const r=memory.hours.find(v=>v.id===h.id&&v.businessId===b.id);if(r)Object.assign(r,{open:!!h.open,openTime:String(h.openTime||'09:00'),closeTime:String(h.closeTime||'18:00')})}}return json(res,200,{ok:true})}
mm=p.match(/^\/api\/appointments\/([^/]+)$/);if(mm&&m==='PATCH'){if(!u)return json(res,401,{error:'Oturumunuz sona ermiş.'});const b=await businessForUser(u),x=await body(req);if(!['pending','completed','cancelled'].includes(x.status))return json(res,400,{error:'Geçersiz durum.'});if(pool){const r=await q('UPDATE appointments SET status=$1 WHERE id=$2 AND business_id=$3 RETURNING id,status',[x.status,mm[1],b.id]);if(!r[0])return json(res,404,{error:'Randevu bulunamadı.'});return json(res,200,{appointment:r[0]})}const a=memory.appointments.find(v=>v.id===mm[1]&&v.businessId===b.id);if(!a)return json(res,404,{error:'Randevu bulunamadı.'});a.status=x.status;return json(res,200,{appointment:a})}
mm=p.match(/^\/api\/public\/([^/]+)$/);if(mm&&m==='GET'){const slug=mm[1];let b;if(pool){b=(await q('SELECT * FROM businesses WHERE slug=$1',[slug]))[0];if(!b)return json(res,404,{error:'Berber bulunamadı.'});const [sv,hr]=await Promise.all([q('SELECT id,name,duration,price FROM services WHERE business_id=$1 ORDER BY name',[b.id]),q('SELECT id,day,open,open_time "openTime",close_time "closeTime" FROM hours WHERE business_id=$1',[b.id])]);return json(res,200,{business:cleanB(b),services:sv,hours:hr})}b=memory.businesses.find(v=>v.slug===slug);if(!b)return json(res,404,{error:'Berber bulunamadı.'});return json(res,200,{business:cleanB(b),services:memory.services.filter(s=>s.businessId===b.id),hours:memory.hours.filter(h=>h.businessId===b.id)})}
mm=p.match(/^\/api\/public\/([^/]+)\/appointments$/);if(mm&&m==='POST'){const slug=mm[1],x=await body(req);let b,services,hours;if(pool){b=(await q('SELECT * FROM businesses WHERE slug=$1',[slug]))[0];services=await q('SELECT * FROM services WHERE business_id=$1',[b?.id]);hours=await q('SELECT * FROM hours WHERE business_id=$1',[b?.id])}else{b=memory.businesses.find(v=>v.slug===slug);services=memory.services.filter(s=>s.businessId===b?.id);hours=memory.hours.filter(h=>h.businessId===b?.id)}if(!b)return json(res,404,{error:'Berber bulunamadı.'});const service=services.find(s=>s.id===x.serviceId);if(!service)return json(res,400,{error:'Hizmet bulunamadı.'});const date=String(x.date||''),time=String(x.time||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!/^\d{2}:\d{2}$/.test(time))return json(res,400,{error:'Tarih veya saat hatalı.'});const d=new Date(date+'T'+time+':00');if(Number.isNaN(d.getTime())||d<new Date())return json(res,400,{error:'Geçmiş bir tarih/saat seçilemez.'});const days=['Pazar','Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'],h=hours.find(v=>v.day===days[d.getDay()]);const ot=h?.openTime||h?.open_time,ct=h?.closeTime||h?.close_time;if(!h||!h.open||time<ot||time>=ct)return json(res,400,{error:'Bu saat çalışma saatleri dışında.'});const customerName=String(x.customerName||'').trim(),phone=String(x.phone||'').trim();if(customerName.length<2||phone.replace(/\D/g,'').length<7)return json(res,400,{error:'Ad soyad ve geçerli telefon gerekli.'});let clashes;if(pool)clashes=await q('SELECT 1 FROM appointments a JOIN services s ON s.id=a.service_id WHERE a.business_id=$1 AND a.date=$2 AND a.status<>\'cancelled\' AND ((a.time::time + (s.duration||0)*interval \'1 minute\')>$3::time AND a.time::time<($3::time + $4*interval \'1 minute\'))',[b.id,date,time,service.duration]);else clashes=memory.appointments.filter(a=>a.businessId===b.id&&a.date===date&&a.status!=='cancelled'&&a.time===time);if(clashes.length)return json(res,409,{error:'Bu saat dolu. Lütfen başka bir saat seç.'});const a={id:id('apt'),businessId:b.id,serviceId:service.id,date,time,customerName,phone,note:String(x.note||'').slice(0,300),status:'pending',createdAt:new Date().toISOString()};if(pool)await q('INSERT INTO appointments(id,business_id,service_id,date,time,customer_name,phone,note,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[a.id,b.id,service.id,date,time,customerName,phone,a.note,'pending']);else memory.appointments.push(a);return json(res,201,{appointment:a})}
return json(res,404,{error:'API endpoint bulunamadı.'})}
function sendFile(res,file){const ext=path.extname(file).toLowerCase(),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json'};fs.readFile(file,(e,d)=>{if(e)return text(res,404,'Not found');res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'});res.end(d)})}
(async()=>{try{await initDb();const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://'+(req.headers.host||'localhost'));if(u.pathname==='/health')return json(res,200,{ok:true,service:APP_NAME,database:!!pool});if(u.pathname.startsWith('/api/'))return api(req,res,u);if(u.pathname.startsWith('/b/'))return sendFile(res,path.join(PUBLIC,'customer.html'));let f=u.pathname==='/'?path.join(PUBLIC,'index.html'):path.join(PUBLIC,u.pathname.replace(/^\//,''));if(!f.startsWith(PUBLIC))return text(res,403,'Forbidden');if(!fs.existsSync(f))f=path.join(PUBLIC,'index.html');sendFile(res,f)}catch(e){console.error(e);json(res,500,{error:'Sunucu hatası. Lütfen tekrar deneyin.'})}});server.listen(PORT,()=>console.log(APP_NAME+' listening on '+PORT))}catch(e){console.error(e);process.exit(1)}})();
